name: pull-request

on:
  issue_comment:
    types:
      - created

jobs:
  coverage:
    if: ( vars.ROLE == 'forgejo-coding' ) && (forgejo.event.comment.body == 'run-coverage')
    runs-on: docker
    container:
      image: 'data.forgejo.org/oci/ci:3'
    services:
      elasticsearch:
        image: data.forgejo.org/oci/bitnami/elasticsearch:7
        options: --tmpfs /bitnami/elasticsearch/data
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      minio:
        image: data.forgejo.org/oci/bitnami/minio:2024.8.17
        options: >-
          --hostname gitea.minio --tmpfs /bitnami/minio/data:noatime
        env:
          MINIO_DOMAIN: minio
          MINIO_ROOT_USER: 123456
          MINIO_ROOT_PASSWORD: 12345678
      ldap:
        image: data.forgejo.org/oci/forgejo-test-openldap:latest
      cacher:
        image: data.forgejo.org/oci/bitnami/redis:7.2
        env:
          ALLOW_EMPTY_PASSWORD: "yes" # redis & valkey will immediately shutdown with no defined password unless overridden
        options: --tmpfs /data:noatime,uid=1000,gid=1000
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: "refs/pull/${{ forgejo.event.issue.number }}/head"
      - uses: ./.forgejo/workflows-composite/setup-env
      - uses: https://data.forgejo.org/actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: playwright-${{ hashFiles('package-lock.json') }}
          path: |
            /home/forgejo/.cache/ms-playwright
      - uses: ./.forgejo/workflows-composite/build-backend
      - run: |
          su forgejo -c 'make coverage-run'
          su forgejo -c 'make coverage-run-sqlite'
          # performance note: oci/ci:3 has the playwright dependencies pre-loaded
          su forgejo -c 'make DEPS_PLAYWRIGHT=true coverage-run-e2e'
          su forgejo -c 'make coverage-merge coverage-show-percentage'
        timeout-minutes: 120
        env:
          TEST_ELASTICSEARCH_URL: http://elasticsearch:9200
          TEST_MINIO_ENDPOINT: minio:9000
          TEST_LDAP: 1
          TEST_REDIS_SERVER: cacher:6379
      - uses: https://codeberg.org/clouds666/unkai@0241847811cf3da3c2c6ad954c10d839c68544d6 # v0.2.9
        with:
          token: ${{ forgejo.TOKEN }}
