name: testing
enable-email-notifications: true

on:
  pull_request:
  push:
    branches:
      - 'forgejo*'
      - 'v*/forgejo*'
  workflow_dispatch:

# for debugging purposes, uncomment to only run a subset of the tests
#env:
#  INTEGRATION_TESTS_ENV: COVERAGE_TEST_ARGS=-run=TestAPIListRepoComments
#  UNIT_TESTS_ENV: COVERAGE_TEST_PACKAGES=forgejo.org/modules/actions
#  E2E_TESTS_ENV: COVERAGE_E2E_RUN="-test.run TestE2e/user-events"

jobs:
  backend-checks:
    if: vars.ROLE == 'forgejo-coding' || vars.ROLE == 'forgejo-testing'
    runs-on: docker
    container:
      image: 'data.forgejo.org/oci/node:24-trixie'
      # options: --tmpfs /tmp:exec,noatime # Too much memory usage
    steps:
      - name: event info
        run: |
          cat <<'EOF'
          ${{ toJSON(github) }}
          EOF
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.forgejo/workflows-composite/setup-env
      # DO NOT add checks here, but rather in the makefile
      - run: su forgejo -c './tools/cimake.sh pr-go'
      # this will re-run the backend target also contained in pr-go, but
      # a re-build is insignificant
      - uses: ./.forgejo/workflows-composite/build-backend
  frontend-checks:
    if: vars.ROLE == 'forgejo-coding' || vars.ROLE == 'forgejo-testing'
    runs-on: docker
    container:
      image: 'data.forgejo.org/oci/node:24-trixie'
      # options: --tmpfs /tmp:exec,noatime # Too much memory usage
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: https://data.forgejo.org/actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version

      - run: make deps-frontend
      - run: make lint-frontend
      - run: make checks-frontend
      - name: make test-frontend-coverage
        run: |
          # Usage of `dayjs` can be impacted by local system timezone and can be sensitive to DST differences; since
          # frontend tests are very short they're run twice with varying DST rules to reduce regression risk.
          TZ=Europe/Berlin make test-frontend-coverage
          TZ=America/Edmonton make test-frontend-coverage
      - run: make frontend
      - name: Install zstd for cache saving
        # works around https://github.com/actions/cache/issues/1169, because the
        # consuming job has zstd and doesn't restore the cache otherwise
        run: |
          apt-get update -qq
          apt-get -q install -qq -y zstd
      - name: 'Cache frontend build for playwright testing'
        uses: https://data.forgejo.org/actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{forgejo.workspace}}/public/assets
          key: frontend-build-${{ forgejo.sha }}
  test-unit:
    if: vars.ROLE == 'forgejo-coding' || vars.ROLE == 'forgejo-testing'
    runs-on: docker
    needs: [backend-checks, frontend-checks]
    container:
      image: 'data.forgejo.org/oci/ci:3'
      # options: --tmpfs /tmp:exec,noatime # Too much memory usage
    services:
      elasticsearch:
        image: data.forgejo.org/oci/bitnami/elasticsearch:7
        options: --tmpfs /bitnami/elasticsearch/data
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      minio:
        image: data.forgejo.org/oci/bitnami/minio:2024.8.17
        options: >-
          --hostname gitea.minio --tmpfs /bitnami/minio/data:noatime
        env:
          MINIO_DOMAIN: minio
          MINIO_ROOT_USER: 123456
          MINIO_ROOT_PASSWORD: 12345678
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.forgejo/workflows-composite/setup-env
      - name: test release-notes-assistant.sh
        run: |
          apt-get -q install -qq -y jq
          ./release-notes-assistant.sh test_main
      - run: |
          su forgejo -c '${{ env.UNIT_TESTS_ENV }} make COVERAGE_TEST_ARGS=-race coverage-run'
          su forgejo -c 'make test-check'
        timeout-minutes: 120
        env:
          RACE_ENABLED: 'true'
          TAGS: bindata
          TEST_ELASTICSEARCH_URL: http://elasticsearch:9200
          TEST_MINIO_ENDPOINT: minio:9000
      - name: upload coverage data
        uses: https://data.forgejo.org/actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{forgejo.workspace}}/coverage/data/unit
          key: coverage-unit-${{ forgejo.sha }}

  test-e2e:
    if: vars.ROLE == 'forgejo-coding' || vars.ROLE == 'forgejo-testing'
    runs-on: docker
    needs: [backend-checks, frontend-checks]
    container:
      image: 'data.forgejo.org/oci/ci:3'
      # options: --tmpfs /tmp:exec,noatime # Too much memory usage
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 20
      - uses: ./.forgejo/workflows-composite/setup-env
      - name: 'Restore frontend build'
        uses: https://data.forgejo.org/actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cache-frontend
        with:
          path: ${{forgejo.workspace}}/public/assets
          key: frontend-build-${{ forgejo.sha }}
      - name: 'Build frontend (if not cached)'
        if: steps.cache-frontend.outputs.cache-hit != 'true'
        run: |
          su forgejo -c 'make deps-frontend frontend'
      - name: Decide to run all tests
        id: run-all
        if: forgejo.event_name == 'push' || contains(forgejo.event.pull_request.labels.*.name, 'run-all-playwright-tests') || contains(forgejo.event.pull_request.title, 'playwright')
        run: |
          echo "all=1" >> "$FORGEJO_OUTPUT"
      - name: Get changed files
        if: forgejo.event_name == 'pull_request'
        id: changed-files
        uses: https://data.forgejo.org/tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          separator: '\n'
      - uses: https://data.forgejo.org/actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: playwright-${{ hashFiles('package-lock.json') }}
          path: |
            /home/forgejo/.cache/ms-playwright
      - run: |
          su forgejo -c 'make generate'
          su forgejo -c '${{ env.E2E_TESTS_ENV }} make coverage-run-e2e'
        timeout-minutes: 120
        env:
          USE_REPO_TEST_DIR: 1
          CHANGED_FILES: ${{steps.changed-files.outputs.all_changed_files}}
          RUN_ALL: ${{steps.run-all.all}}
      - name: Upload test artifacts on failure
        if: failure()
        uses: https://data.forgejo.org/forgejo/upload-artifact@cb8afe72b42edc798abfb8fcb556cf660d894245 # v5
        with:
          name: test-artifacts.zip
          path: tests/e2e/test-artifacts/
          retention-days: 3
      - name: upload coverage data
        uses: https://data.forgejo.org/actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{forgejo.workspace}}/coverage/data/e2e
          key: coverage-e2e-${{ forgejo.sha }}

  test-remote-cacher:
    if: vars.ROLE == 'forgejo-coding' || vars.ROLE == 'forgejo-testing'
    runs-on: docker
    needs: [backend-checks, frontend-checks, test-unit]
    container:
      image: 'data.forgejo.org/oci/node:24-trixie'
      # options: --tmpfs /tmp:exec,noatime # Too much memory usage
    name: ${{ format('test-remote-cacher ({0})', matrix.cacher.name) }}
    strategy:
      matrix:
        cacher:
          - name: redis
            image: data.forgejo.org/oci/bitnami/redis:7.2
            options: --tmpfs /bitnami/redis/data:noatime
          - name: valkey
            image: data.forgejo.org/oci/bitnami/valkey:7.2
            options: --tmpfs /bitnami/redis/data:noatime
          - name: garnet
            image: ghcr.io/microsoft/garnet-alpine:1.0.14
            options: --tmpfs /data:noatime
    services:
      cacher:
        image: ${{ matrix.cacher.image }}
        options: ${{ matrix.cacher.options }}
        env:
          ALLOW_EMPTY_PASSWORD: 'yes' # redis & valkey will immediately shutdown with no defined password unless overridden
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.forgejo/workflows-composite/setup-env
      - run: |
          su forgejo -c 'make test-remote-cacher test-check'
        timeout-minutes: 120
        env:
          RACE_ENABLED: 'true'
          TAGS: bindata
          TEST_REDIS_SERVER: cacher:6379
  test-mysql:
    if: vars.ROLE == 'forgejo-coding' || vars.ROLE == 'forgejo-testing'
    runs-on: docker
    needs: [backend-checks, frontend-checks]
    container:
      image: 'data.forgejo.org/oci/node:24-trixie'
      # options: --tmpfs /tmp:exec,noatime # Too much memory usage
    services:
      mysql:
        image: 'data.forgejo.org/oci/bitnami/mysql:8.4'
        env:
          ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: testgitea
          #
          # See also https://codeberg.org/forgejo/forgejo/issues/976
          #
          MYSQL_EXTRA_FLAGS: --innodb-adaptive-flushing=OFF --innodb-buffer-pool-size=4G --innodb-log-buffer-size=128M --innodb-flush-log-at-trx-commit=0 --innodb-flush-log-at-timeout=30 --innodb-flush-method=nosync --innodb-fsync-threshold=1000000000 --disable-log-bin
        options: --tmpfs /bitnami/mysql/data:noatime
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.forgejo/workflows-composite/setup-env
      - name: install dependencies
        run: apt-get update -qq && apt-get -q install -qq -y git-lfs
        env:
          DEBIAN_FRONTEND: noninteractive
      - run: |
          su forgejo -c 'make test-mysql-migration test-mysql'
        timeout-minutes: 120
        env:
          USE_REPO_TEST_DIR: 1
  test-pgsql:
    if: vars.ROLE == 'forgejo-coding' || vars.ROLE == 'forgejo-testing'
    runs-on: docker
    needs: [backend-checks, frontend-checks]
    container:
      image: 'data.forgejo.org/oci/node:24-trixie'
      # options: --tmpfs /tmp:exec,noatime # Too much memory usage
    services:
      minio:
        image: data.forgejo.org/oci/bitnami/minio:2024.8.17
        env:
          MINIO_ROOT_USER: 123456
          MINIO_ROOT_PASSWORD: 12345678
        options: --tmpfs /bitnami/minio/data
      ldap:
        image: data.forgejo.org/oci/forgejo-test-openldap:1
        options: --memory 500M
      pgsql:
        image: data.forgejo.org/oci/bitnami/postgresql:16
        env:
          POSTGRESQL_DATABASE: test
          POSTGRESQL_PASSWORD: postgres
          POSTGRESQL_FSYNC: off
          POSTGRESQL_EXTRA_FLAGS: -c full_page_writes=off
        options: --tmpfs /bitnami/postgresql
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.forgejo/workflows-composite/setup-env
      - name: install dependencies
        run: apt-get update -qq && apt-get -q install -qq -y git-lfs
        env:
          DEBIAN_FRONTEND: noninteractive
      - run: |
          su forgejo -c 'make test-pgsql-migration test-pgsql'
        timeout-minutes: 120
        env:
          RACE_ENABLED: true
          USE_REPO_TEST_DIR: 1
          TEST_LDAP: 1
  test-sqlite:
    if: vars.ROLE == 'forgejo-coding' || vars.ROLE == 'forgejo-testing'
    runs-on: docker
    needs: [backend-checks, frontend-checks]
    container:
      image: 'data.forgejo.org/oci/ci:3'
      # options: --tmpfs /tmp:exec,noatime # Too much memory usage
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.forgejo/workflows-composite/setup-env
      - name: install dependencies
        run: apt-get update -qq && apt-get -q install -qq -y git-lfs
        env:
          DEBIAN_FRONTEND: noninteractive
      - run: |
          su forgejo -c 'make test-sqlite-migration'
          su forgejo -c '${{ env.INTEGRATION_TESTS_ENV }} make coverage-run-sqlite'
        timeout-minutes: 120
        env:
          TAGS: sqlite sqlite_unlock_notify
          TEST_TAGS: sqlite sqlite_unlock_notify
          USE_REPO_TEST_DIR: 1
      - name: upload coverage data
        uses: https://data.forgejo.org/actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{forgejo.workspace}}/coverage/data/sqlite
          key: coverage-sqlite-${{ forgejo.sha }}
  coverage:
    if: vars.ROLE == 'forgejo-coding' || vars.ROLE == 'forgejo-testing'
    runs-on: docker
    container:
      image: 'data.forgejo.org/oci/ci:3'
    needs: [test-unit, test-e2e, test-sqlite]
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.forgejo/workflows-composite/setup-env
      - id: coverage-unit
        uses: https://data.forgejo.org/actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{forgejo.workspace}}/coverage/data/unit
          key: coverage-unit-${{ forgejo.sha }}
      - id: coverage-e2e
        uses: https://data.forgejo.org/actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{forgejo.workspace}}/coverage/data/e2e
          key: coverage-e2e-${{ forgejo.sha }}
      - id: coverage-sqlite
        uses: https://data.forgejo.org/actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{forgejo.workspace}}/coverage/data/sqlite
          key: coverage-sqlite-${{ forgejo.sha }}
      - name: show missing coverage data
        if: "! steps.coverage-unit.outputs.cache-hit || ! steps.coverage-e2e.outputs.cache-hit || ! steps.coverage-sqlite.outputs.cache-hit"
        run: |
          echo "found unit coverage data = ${{ steps.coverage-unit.outputs.cache-hit }}"
          echo "found e2e coverage data = ${{ steps.coverage-e2e.outputs.cache-hit }}"
          echo "found sqlite coverage data = ${{ steps.coverage-sqlite.outputs.cache-hit }}"
      - name: merge and convert coverage data
        if: steps.coverage-unit.outputs.cache-hit && steps.coverage-e2e.outputs.cache-hit && steps.coverage-sqlite.outputs.cache-hit
        run: |
          make coverage-show-percentage
      - if: forgejo.event_name == 'pull_request' && (steps.coverage-unit.outputs.cache-hit && steps.coverage-e2e.outputs.cache-hit && steps.coverage-sqlite.outputs.cache-hit)
        name: create or update the coverage report in a pull request comment
        uses: https://codeberg.org/clouds666/unkai@85dc8d9796ff06473dfd773c5883cfb8be1045ce # v0.2.13
        with:
          token: ${{ forgejo.TOKEN }}
      - if: forgejo.event_name != 'pull_request' && (steps.coverage-unit.outputs.cache-hit && steps.coverage-e2e.outputs.cache-hit && steps.coverage-sqlite.outputs.cache-hit)
        name: upload the converted coverage data (textfmt.out)
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: coverage
          path: coverage/textfmt.out
          retention-days: 1

  security-check:
    if: vars.ROLE == 'forgejo-coding' || vars.ROLE == 'forgejo-testing'
    runs-on: docker
    needs:
      - test-sqlite
      - test-pgsql
      - test-mysql
      - test-remote-cacher
      - test-unit
    container:
      image: 'data.forgejo.org/oci/node:24-trixie'
      # options: --tmpfs /tmp:exec,noatime # Too much memory usage
    steps:
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.forgejo/workflows-composite/setup-env
      - run: su forgejo -c 'make deps-backend deps-tools'
      - run: su forgejo -c 'make security-check'
  semgrep:
    if: vars.ROLE == 'forgejo-coding' || vars.ROLE == 'forgejo-testing'
    name: semgrep/ci
    runs-on: docker
    container:
      image: 'data.forgejo.org/oci/semgrep:latest'
    steps:
      - run: apk add nodejs # required for actions/checkout
      - uses: https://data.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: self-check semgrep rules
        run: |
          set -x
          semgrep validate .semgrep/config
          semgrep --test .semgrep/tests/ --config .semgrep/config/
      - name: semgrep ci
        run: semgrep ci --config .semgrep/config/ --metrics=off
