rules:
  - id: test-missing-setup-function
    patterns:
      - pattern: |
          func $F(t *testing.T) {
            ...
          }
      - pattern-not: |
          func $F(t *testing.T) {
            testhelper.Setup(t, ...)
            ...
          }
      - metavariable-regex:
          metavariable: $F
          regex: '(Test\w+)'

    paths:
      include:
        - /**/*_test.go
    # reminder to not try to implement autofix, it breaks Go code as of v1.175.0
    #fix: |
    #  func $F(t *testing.T) {
    #    testhelper.Setup(t)
    #    $...BODY
    #  }
    languages:
      - go
    message: All test must call first testhelper.Setup(t)
    severity: ERROR
