// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package system

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStateStore creates a new instance of MockStateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateStore(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockStateStore {
	mock := &MockStateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStateStore is an autogenerated mock type for the StateStore type
type MockStateStore struct {
	mock.Mock
}

type MockStateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateStore) EXPECT() *MockStateStore_Expecter {
	return &MockStateStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockStateStore
func (_mock *MockStateStore) Get(ctx context.Context, item StateItem) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, StateItem) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStateStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStateStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - item StateItem
func (_e *MockStateStore_Expecter) Get(ctx, item any) *MockStateStore_Get_Call {
	return &MockStateStore_Get_Call{Call: _e.mock.On("Get", ctx, item)}
}

func (_c *MockStateStore_Get_Call) Run(run func(ctx context.Context, item StateItem)) *MockStateStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 StateItem
		if args[1] != nil {
			arg1 = args[1].(StateItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStateStore_Get_Call) Return(err error) *MockStateStore_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStateStore_Get_Call) RunAndReturn(run func(ctx context.Context, item StateItem) error) *MockStateStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockStateStore
func (_mock *MockStateStore) Set(ctx context.Context, item StateItem) error {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, StateItem) error); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStateStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockStateStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - item StateItem
func (_e *MockStateStore_Expecter) Set(ctx, item any) *MockStateStore_Set_Call {
	return &MockStateStore_Set_Call{Call: _e.mock.On("Set", ctx, item)}
}

func (_c *MockStateStore_Set_Call) Run(run func(ctx context.Context, item StateItem)) *MockStateStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 StateItem
		if args[1] != nil {
			arg1 = args[1].(StateItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStateStore_Set_Call) Return(err error) *MockStateStore_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStateStore_Set_Call) RunAndReturn(run func(ctx context.Context, item StateItem) error) *MockStateStore_Set_Call {
	_c.Call.Return(run)
	return _c
}
